### PR TITLE
Security: Removing the hard-coded metrics tag

### PR DESCRIPTION
**Pull request by aTastyCookie**
Removing the hard-coded metrics tag and replacing the analytics script URL with the official one

### CODE REVIEW

**Comment by aTastyCookie** [comment]
Around 1000+ sites using your addon https://publicwww.com/websites/mc.yandex.ru%2Fwatch%2F5695870/

**Comment by mihdan** [comment]
@aTastyCookie 

cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js - this is the official alternative address that was created for countries where Yandex is blocked (for example Ukraine).

**Comment by mihdan** [comment]
https://github.com/wpl-agency/events-tracker-for-elementor/commit/b91c884ad82fb5eb13bfbcc93aedb33dc661158d

**Comment by aTastyCookie** [comment]
Ok, thanks for the information about the alternative address where Yandex is blocked. Also, for removing the hard-coded metrics tag ;)

**Pull request closed without merging**
